### ISSUE TITLE
project failed to build

### ISSUE THREAD

**Issue by ghost** [ClementDreptin/GameShortcut#1]
XLAST file successfully generated.
blast : error : Project failed to load
Press any key to continue . . .

thats what i get.
i've installed everything i need

**Comment by ClementDreptin** [comment]
No matter what error I try to inject I cannot reproduce your error so you're going to have to provide more information. Did you compile from source or did you use the prebuilt binaries from the releases section? Do you have your console properly set up in Neighborhood? Did you install the full version of the XDK or just the minimal one?
